apiVersion: batch/v1
kind: Job
metadata:
  name: cntwa-job
spec:
  template:
    spec:
      containers:
      - name: cntwa-job
        image: yash5090/cntwa:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
