apiVersion: apps/v1
kind: Deployment
metadata:
  name: cntwa-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cntwa
  template:
    metadata:
      labels:
        app: cntwa
    spec:
      containers:
        - name: cntwa
          image: yash5090/cntwa:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
